"""Target driven by the official Nav2 stack.

Nothing of Nav2 is rewritten here. This file only:

  1. loads the official nav2_params.yaml installed with nav2_bringup and
     applies the few keys in config/nav2_overrides.yaml, plus the AMCL
     initial pose taken from worlds.TARGET_SPAWN;
  2. publishes the one static transform the target model does not provide
     (target/base_footprint -> target/base_scan), on /target/tf_static;
  3. includes the official nav2_bringup/bringup_launch.py in the /target
     namespace, with the map generated by scripts/generate_map.py;
  4. starts target_driver_nav2_node, adapted from the nav2_simple_commander
     patrol demo, which sends the waypoints of trajectories.py.

Everything Nav2 does lives under /target, including its TF (/target/tf), so
the follower's tree on /tf never sees a map frame or the target's frames.

It is included by main.launch.py; on its own it expects the simulation to be
already running.
"""
import os
import tempfile

import yaml
from ament_index_python.packages import get_package_share_directory

from leader_follower import worlds
from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, IncludeLaunchDescription,
                            OpaqueFunction)
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

NAMESPACE = 'target'
MAP_FILE = 'leader_follower_simple.yaml'


def deep_merge(base, over):
    # Recursive dict update: only the leaves present in `over` change.
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            deep_merge(base[k], v)
        else:
            base[k] = v
    return base


def launch_setup(context, *args, **kwargs):
    pkg = get_package_share_directory('leader_follower')
    nav2 = get_package_share_directory('nav2_bringup')

    with open(os.path.join(nav2, 'params', 'nav2_params.yaml')) as f:
        params = yaml.safe_load(f)
    with open(os.path.join(pkg, 'config', 'nav2_overrides.yaml')) as f:
        deep_merge(params, yaml.safe_load(f))

    x, y, yaw = worlds.TARGET_SPAWN
    deep_merge(params, {'amcl': {'ros__parameters': {
        'initial_pose': {'x': x, 'y': y, 'z': 0.0, 'yaw': yaw}}}})

    merged = os.path.join(tempfile.gettempdir(), 'leader_follower_nav2_params.yaml')
    with open(merged, 'w') as f:
        yaml.safe_dump(params, f, sort_keys=False)

    use_sim_time = LaunchConfiguration('use_sim_time')

    # Scan frame of the target: same offset as the <sensor> pose in
    # models/turtlebot3_target/model.sdf. The DiffDrive plugin publishes only
    # odom -> base_footprint, so this is the only missing link.
    #
    # Namespaced and remapped exactly like nav2_bringup remaps every one of
    # its own nodes (see bringup_launch.py: remappings = [('/tf', 'tf'),
    # ('/tf_static', 'tf_static')]) rather than hard-coding the destination
    # topic: tf2 broadcasters publish on the relative 'tf_static' by default,
    # but some remap it as absolute internally regardless, so Nav2's own
    # pattern is to force it relative and let the node's namespace prefix it.
    # Following that convention here means this survives a NAMESPACE change
    # without being touched, same as Nav2's own nodes.
    scan_tf = Node(
        package='tf2_ros', executable='static_transform_publisher',
        name='target_scan_tf', namespace=NAMESPACE, output='screen',
        arguments=['--x', '-0.032', '--y', '0', '--z', '0.171',
                   '--frame-id', f'{NAMESPACE}/base_footprint',
                   '--child-frame-id', f'{NAMESPACE}/base_scan'],
        parameters=[{'use_sim_time': use_sim_time}],
        remappings=[('/tf_static', 'tf_static')])

    bringup = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(nav2, 'launch', 'bringup_launch.py')),
        launch_arguments={
            'namespace': NAMESPACE,
            'use_namespace': 'True',
            'slam': 'False',
            'map': os.path.join(pkg, 'maps', MAP_FILE),
            'use_sim_time': use_sim_time,
            'params_file': merged,
            'autostart': 'True',
            'use_composition': 'False',
            'use_respawn': 'False',
        }.items())

    client = Node(
        package='leader_follower', executable='target_driver_nav2_node',
        name='target_driver_nav2_node', namespace=NAMESPACE, output='screen',
        parameters=[{'use_sim_time': use_sim_time,
                     'trajectory': LaunchConfiguration('trajectory')}])

    return [scan_tf, bringup, client]


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('use_sim_time', default_value='true'),
        DeclareLaunchArgument('trajectory', default_value=worlds.DEFAULT_TRAJECTORY),
        OpaqueFunction(function=launch_setup),
    ])

