"""Generates the .world file of the test arena.

Writing it by hand would work too, but generating it from the geometry declared
in worlds.py is the only way to guarantee that the world Gazebo loads and the
model the trajectories are validated against cannot diverge. When they were
described in two places, they did.
"""
import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'leader_follower'))

from leader_follower import worlds  # noqa: E402

WALL_H = 1.0            # height of walls and blades
WALL_T = 0.1            # thickness

WALL_COLOR = (0.85, 0.85, 0.90)
BLADE_COLOR = (0.72, 0.72, 0.78)

PREAMBLE = '''    <scene>
      <ambient>0.9 0.9 0.9 1</ambient>
      <background>0.8 0.85 0.9 1</background>
      <shadows>false</shadows>
    </scene>

    <!-- 2 ms step instead of 1: half the physics steps for the same amount
         of simulated time, and stable with two differential-drive robots -->
    <physics type="ode">
      <max_step_size>0.002</max_step_size>
      <real_time_factor>1</real_time_factor>
    </physics>

    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>

    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.75 0.75 0.75 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>0.3 0.2 -0.9</direction>
    </light>

    <model name="ground">
      <static>true</static>
      <link name="link">
        <collision name="c">
          <geometry><plane><normal>0 0 1</normal><size>40 40</size></plane></geometry>
        </collision>
        <visual name="v">
          <geometry><plane><normal>0 0 1</normal><size>40 40</size></plane></geometry>
          <material>
            <ambient>0.68 0.68 0.68 1</ambient>
            <diffuse>0.68 0.68 0.68 1</diffuse>
          </material>
        </visual>
      </link>
    </model>
'''


def header(description):
    return f'''<?xml version="1.0"?>
<!-- World for the leader-follower project.

     A 10 x 8 m rectangle enclosed by walls, with a two-blade chicane whose
     gaps alternate. There is no geometric occlusion here: losses of the target
     come from the incidence angle on the marker alone.

     Generated by scripts/generate_world.py from the geometry in
     leader_follower/worlds.py, so the simulated arena and the model used to
     validate the waypoints cannot diverge.

     Ground plane and light are defined locally, because the official worlds
     fetch them from Gazebo Fuel and that requires a connection. -->
<sdf version="1.8">
  <world name="leader_follower">

{PREAMBLE}'''


def box(name, x, y, sx, sy, sz, rgb, z=None):
    z = sz / 2 if z is None else z
    r, g, b = rgb
    return f'''
    <model name="{name}">
      <static>true</static>
      <link name="link">
        <pose>{x} {y} {z} 0 0 0</pose>
        <visual name="v">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
          <material>
            <ambient>{r} {g} {b} 1</ambient>
            <diffuse>{r} {g} {b} 1</diffuse>
          </material>
        </visual>
        <collision name="c">
          <geometry><box><size>{sx} {sy} {sz}</size></box></geometry>
        </collision>
      </link>
    </model>'''


def panels(spec):
    """The three fixed markers.

    The panel is thin along Y, so with yaw 0 its textured face looks along
    +/-y. The wrong yaw leaves it edge-on against the wall like a blade, and
    the detector never sees it at all.
    """
    return [f'''
    <include>
      <name>aruco_marker_{mid}</name>
      <uri>model://aruco_marker_{mid}</uri>
      <pose>{x} {y} 0.4 0 0 {yaw}</pose>
    </include>''' for x, y, yaw, mid in spec]


def write_world(path, parts):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(''.join(parts) + '\n\n  </world>\n</sdf>\n')
    print(f"written {os.path.normpath(path)}")


def generate_simple(outdir):
    """The arena: a rectangle with a two-blade chicane.

    No obstacles scattered at random: the two blades have alternating gaps and
    force the route to weave, so every element of the map has a function.
    """
    half_w, half_h = worlds.RECT

    parts = [header(
        f"Simple arena: {2 * half_w:.0f} x {2 * half_h:.0f} m rectangle with\n"
        "     a two-blade chicane with alternating gaps. Reference\n"
        "     arena: no geometric occlusion, the losses\n"
        "     of the target come from the marker incidence angle alone.")]

    parts.append(box('wall_north', 0, half_h, 2 * half_w + 2 * WALL_T, WALL_T,
                     WALL_H, WALL_COLOR))
    parts.append(box('wall_south', 0, -half_h, 2 * half_w + 2 * WALL_T, WALL_T,
                     WALL_H, WALL_COLOR))
    parts.append(box('wall_east', half_w, 0, WALL_T, 2 * half_h,
                     WALL_H, WALL_COLOR))
    parts.append(box('wall_west', -half_w, 0, WALL_T, 2 * half_h,
                     WALL_H, WALL_COLOR))

    for i, (x, y0, y1) in enumerate(worlds.WALLS):
        parts.append(box(f'chicane_{i}', x, (y0 + y1) / 2, WALL_T, y1 - y0,
                         WALL_H, BLADE_COLOR))

    parts += panels(worlds.MARKERS)
    write_world(os.path.join(outdir, worlds.WORLD_FILE), parts)
    print(f"  rectangle {2 * half_w:.0f} x {2 * half_h:.0f} m, chicane with "
          f"{len(worlds.WALLS)} blades, {len(worlds.MARKERS)} panels")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    outdir = os.path.join(here, '..', 'src', 'leader_follower', 'worlds')
    generate_simple(outdir)


if __name__ == '__main__':
    main()
